"""Workout to workout

Revision ID: 10c1dbdf7b09
Revises: 8c04d0413f94
Create Date: 2025-09-13 15:46:13.195677

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10c1dbdf7b09"
down_revision: Union[str, Sequence[str], None] = "8c04d0413f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("Workout", "workout")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("workout", "Workout")
    # ### end Alembic commands ###
