"""cascade added on workouts

Revision ID: 23effc02c015
Revises: 660abb62900a
Create Date: 2025-09-13 16:06:39.468243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23effc02c015'
down_revision: Union[str, Sequence[str], None] = '660abb62900a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workout_excercise_id_fkey'), 'workout', type_='foreignkey')
    op.drop_constraint(op.f('workout_user_id_fkey'), 'workout', type_='foreignkey')
    op.create_foreign_key(None, 'workout', 'excercises', ['excercise_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workout', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout', type_='foreignkey')
    op.drop_constraint(None, 'workout', type_='foreignkey')
    op.create_foreign_key(op.f('workout_user_id_fkey'), 'workout', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('workout_excercise_id_fkey'), 'workout', 'excercises', ['excercise_id'], ['id'])
    # ### end Alembic commands ###
