"""Workout to workout tablename

Revision ID: 660abb62900a
Revises: 10c1dbdf7b09
Create Date: 2025-09-13 15:47:40.808209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660abb62900a'
down_revision: Union[str, Sequence[str], None] = '10c1dbdf7b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('excercise_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('rest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['excercise_id'], ['excercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Workout')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Workout',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('excercise_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rest', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excercise_id'], ['excercises.id'], name=op.f('Workout_excercise_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('Workout_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Workout_pkey'))
    )
    op.drop_table('workout')
    # ### end Alembic commands ###
