"""added tier and years

Revision ID: ffea2cd4d657
Revises: 19d339e39fb7
Create Date: 2025-09-07 18:11:08.286240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffea2cd4d657'
down_revision: Union[str, Sequence[str], None] = '19d339e39fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'years')
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###
